[build]
builder = "nixpacks"

# Main service (if you have one)
[deploy]
startCommand = "echo 'Cron jobs configured'"

# MTA Rush Hour Data Collection - Morning Rush (7-10 AM) every 15 minutes on weekdays
[[services]]
name = "mta-morning-rush"
source = "."
cronSchedule = "*/15 7-9 * * 1-5"  # Every 15 minutes from 7-9:59 AM, Mon-Fri
startCommand = "python3 collect_real_time_mta_info.py"

# MTA Rush Hour Data Collection - Evening Rush (4-7 PM) every 15 minutes on weekdays  
[[services]]
name = "mta-evening-rush"
source = "."
cronSchedule = "*/15 16-18 * * 1-5"  # Every 15 minutes from 4-6:59 PM, Mon-Fri
startCommand = "python3 collect_real_time_mta_info.py"

# Weather Data Collection - 11:50 PM on weekdays
[[services]]
name = "weather-collection"
source = "."
cronSchedule = "50 23 * * 1-5"  # 11:50 PM, Mon-Fri
startCommand = "python3 collect_weather_info.py"
