# .github/workflows/data-collection.yml
name: MTA and Weather Data Collection

on:
  workflow_dispatch:
    inputs:
      job_type:
        description: 'Which job to run'
        required: true
        default: 'both'
        type: choice
        options:
        - mta
        - weather
        - both

jobs:
  collect-mta-data:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.job_type || github.event.inputs.job_type == 'mta' || github.event.inputs.job_type == 'both' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests sqlalchemy psycopg2-binary nyct-gtfs
      
      - name: Test MTA script
        run: |
          echo "Would run MTA data collection here"
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la

  collect-weather-data:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.job_type || github.event.inputs.job_type == 'weather' || github.event.inputs.job_type == 'both' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests sqlalchemy psycopg2-binary
      
      - name: Test weather script
        run: |
          echo "Would run weather data collection here"
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
