# .github/workflows/scheduled-data-collection.yml
name: Scheduled Data Collection

on:
  schedule:
    # MTA Morning Rush: 7-9 AM EST = 12-2 PM UTC
    - cron: '0 12-14 * * 1-5'    # Top of each hour
    - cron: '15 12-14 * * 1-5'   # Quarter past
    - cron: '30 12-14 * * 1-5'   # Half past  
    - cron: '45 12-14 * * 1-5'   # Quarter to
    
    # MTA Evening Rush: 5-7 PM EST = 10 PM-12 AM UTC
    - cron: '0 22-24 * * 1-5'    # Top of each hour
    - cron: '15 22-24 * * 1-5'   # Quarter past
    - cron: '30 22-24 * * 1-5'   # Half past
    - cron: '45 22-24 * * 1-5'   # Quarter to
    
    # Weather: Weekdays at 11:50 PM EST = 4:50 AM UTC next day
    - cron: '50 4 * * 2-6'       # Tue-Sat at 4:50 AM UTC (Mon-Fri 11:50 PM EST)

jobs:
  collect-mta-data:
    runs-on: ubuntu-latest
    # Only run for MTA schedules (not weather)
    if: ${{ !contains(github.event.schedule, '50 4') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests sqlalchemy psycopg2-binary nyct-gtfs
      
      - name: Create data_files directory
        run: mkdir -p data_files
      
      - name: Run MTA data collection
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Starting scheduled MTA data collection at $(date -u) UTC"
          python collect_real_time_mta_info.py
          echo "Finished scheduled MTA data collection at $(date -u) UTC"

  collect-weather-data:
    runs-on: ubuntu-latest
    # Only run for weather schedule
    if: ${{ contains(github.event.schedule, '50 4') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests sqlalchemy psycopg2-binary
      
      - name: Run weather data collection
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Starting scheduled weather data collection at $(date -u) UTC"
          python collect_weather_info.py
          echo "Finished scheduled weather data collection at $(date -u) UTC"
