name: Test Schedule Debug

on:
  schedule:
    # Simple test - every 5 minutes
    - cron: '*/1 * * * *'

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Test scheduled run
        run: |
          echo "Scheduled test ran at $(date -u) UTC"
          echo "This confirms scheduling works!"
